accountapp/urls.py
from django.urls import path

from accountapp.views import  AccountCreateView, AccountDetailView, AccountUpdateView, AccountDeleteView

from django.contrib.auth.views import LoginView, LogoutView

app_name = 'accountapp'

urlpatterns = [
    path('login/', LoginView.as_view(template_name= 'accountapp/login.html'),
         name= 'login'  ),
    #path (어떤주소로 들어올건지, 함수(클래스시: 클래스이름.as_view), 우리가 쓸 라우트의 이름)

    path('logout/', LogoutView.as_view(), name='logout'),

    path('create/', AccountCreateView.as_view(), name = 'create'),
    #path ( 파일 이름, 함수(클래스시: 클래스이름.as_view), 우리가 쓸 이름을 설정)
    # 어떤 url 로 가야 회원가입 로직으로 가는지


    # detailView 만든 후 라우팅
    path('detail/<int:pk>', AccountDetailView.as_view(), name = 'detail' ),
    # 어떤주소로 접글할때 로직을 실행할건지 / 로직  / 라우트의 이름
    # int : pk  = 인티저 형태를 받는데 이름은 pk 이다

    path('update/<int:pk>', AccountUpdateView.as_view(), name ='update'),
    # 어떤주소로 접근할지 / 로직 / 라우트의 이름

    path('delete/<int:pk>', AccountDeleteView.as_view(), name = 'delete')
]
# 앱 네임이 accountapp 인걸로 가서 url이 hello_world 로 가라

goHome/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

from articleapp.views import ArticleListView

urlpatterns = [
    path('', ArticleListView.as_view(), name='home'),
    path('admin/', admin.site.urls),        # 장고가 기본적으로 준 주소 (관리자 페이지)
    path('accounts/', include('accountapp.urls')),         #path = 장고에서 제공하는 기능 , 경로를 accounts
    path('profiles/', include('profileapp.urls')),
    # profiles 로가는 겨올를 설정
    path('articles/', include('articleapp.urls')),
    path('comments/', include('commentapp.urls')),
    path('projects/', include('projectapp.urls')),
    path('subscribe/', include('subscribeapp.urls')),
    path('likes/', include('likeapp.urls')),

] + static(settings.MEDIA_URL, document_root = settings.MEDIA_ROOT )
# 이미지 모양을 되기 위해 media 에 static 을 가져옴
# 경로로 왔을 때, 미디어를 제공

profileapp/urls.py
from django.urls import path

from profileapp.views import ProfileCreateView, ProfileUpdateView

app_name = 'profileapp'


urlpatterns =[

# 로직을 트리거할 주소

    path('create/', ProfileCreateView.as_view(),name='create'),
    path('update/<int:pk>', ProfileUpdateView.as_view(),name='update'),


]

accountapp/models.py
from django.db import models

# Create your models here.
class NewModel(models.Model):
    text = models.CharField(max_length=255,null=False)
    # charfield : 문자열 받음 ,max_length : 최대 문자열 255, null = 공란의 여부


# Model 를 상속받아 모델 형태에서 어떤형식으로 데이터를 받을 지 적어놈

articleapp/models.py
from django.contrib.auth.models import User
from django.db import models

# Create your models here.
from projectapp.models import Project


class Article(models.Model):
    writer = models.ForeignKey(User, on_delete=models.SET_NULL, related_name='article',      # 접근할 이름 target_user.article 이렇게 됨
    null=True)
        # 1대 다로 테이블과 테이블을 연결함  ,,, User 을 연결
        # on_delete : user 가 삭제 되었을 떄 하는 것
        # null 값도 ok 하다는 것임

    project = models.ForeignKey(Project, on_delete=models.SET_NULL,
                                related_name='article', null=True, blank=True)

    title = models.CharField(max_length=200, null=True)
    image =models.ImageField(upload_to='article/', null=True)
    # media 파일 안에 article 이라는 폴더가 생기고 그 안에 사진이 자동으로 업로드됨

    content = models.TextField(null=True)
    #  TextField: 장문을 이용 시 사용

    created_at = models.DateField(auto_now_add=True, null=True)
    # DateField : 언제작성했는지 알 수 있음
    # auto_now_add : 자동으로 시간을 작성해줌줌

    like = models.IntegerField(default=0)

accountapp/forms.py
from django.contrib.auth.forms import UserCreationForm


class AccountCreationForm(UserCreationForm):
    def __init__(self, *args, **kwargs):
        # 초기화
        super().__init__(*args, **kwargs)
        # super : 부모의 메서드를 가져옴

        self.fields['username'].disabled = True
        # username 이라는 속성을 찾고 비활성화 함(f12 에서 수정해도 그대로임)
        # fields : update 할때의 항목들


#오버라이딩 : 부모의 메서드를 덮어씌움
# 아이디를 비활성화 하게 함

accountapp/views.py
from django.contrib.auth.decorators import login_required
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth.models import User
from django.http import HttpResponseRedirect
from django.shortcuts import render

# Create your views here.
from django.urls import reverse, reverse_lazy
from django.utils.decorators import method_decorator
from django.views.generic import CreateView, DetailView, UpdateView, DeleteView
from django.views.generic.list import MultipleObjectMixin

from accountapp.forms import AccountCreationForm
from accountapp.models import NewModel


# (login_url= reverse_lazy('accountapp:login'))
# login_url 에 직접적인 주소가 아닌 reverse_lazy로 역추적해서 하면됨
from accountapp.decorators import account_ownership_required


# @login_required
# 이거 쓰면 자동적으로 로그인 화면으로 감
from articleapp.models import Article

# 지워주기 8/27
# def hello_world(request):
#
#
#     if request.method == 'POST':
#         # request 장고에서 지원하는 객체에 method 라는 저장공간이 있음
#         temp = request.POST.get('input_text')
#         #  요청정보가 request 로 들어가므로 // input_text 를 불러옴
#
#         new_model =NewModel()         # 변수에 정의한 클래스를 가져옴
#         new_model.text = temp
#         new_model.save()            # DB에 저장
#
#         # data_list = NewModel.objects.all()
#         # 뉴모델 안에있는 모든 값들이 data_list 에 저장됨
#
#         return  HttpResponseRedirect(reverse('accountapp:hello_world'))
#                 #  이 주소로 가라
#
#
# # return  render(request,'accountapp/hello_world.html'
# #                ,context={'new_modeltext':temp })     # 텍스트 창에서 입력한 글자가 바로 밑에 출력이 가능하도록 함
#      # HttpResponse 라는 객체를 반환    // 여기에 출력
#      # 붉은색 표시일때 alt+enter 눌러서 from.... 누르면 import 할 필요 x
#
#
#     else:
#         data_list = NewModel.objects.all()
#         # 뉴모델 안에있는 모든 값들이 data_list 에 저장됨
#         return render(request, 'accountapp/hello_world.html'
#                       , context={'data_list': data_list})




# 클래스 선언
# 회원가입 로직 만들기
class AccountCreateView(CreateView):            # 장고의 create 를 사용함
    model = User         # 계정을 받는거는 특별한 작업이이때문에 장고가 기본적으로 제공해주는 user을 사용
    form_class = UserCreationForm
    # 일반적으로 장고에서 제공하는 sign up 화면폼이라 생각하자

    success_url =  reverse_lazy('articleapp:list')
    # 회원가입이 성공시 가야하는 url
    #( 함수에서 불러오는 방식 = reverse // 클래스에서 불러오는 방식 = reverse_lazy)
    # 클래스에서 리버스 쓸때는 에러가 생김
    template_name = 'accountapp/create.html'

class AccountDetailView(DetailView, MultipleObjectMixin):    # 장고의 디테일 뷰를 상속받는 클래스를 생성
    model = User
    context_object_name = 'target_user'
    # 상세 계정을 뽑아낼 변수를 추출

    template_name = 'accountapp/detail.html'
    # 상세정보를 할때 어떤 걸로 랜더링할지
    paginate_by = 20

    def get_context_data(self, **kwargs):
        article_list = Article.objects.filter(writer=self.object)
        return super().get_context_data(object_list=article_list, **kwargs)

has_ownership  = [login_required, account_ownership_required]
# 이렇게 할 시 4줄 말고 2줄로 줄일 수 있음
# 4 줄로 할 시
# @method_decorator(login_required, 'get')
# @method_decorator(login_required, 'post')
# @method_decorator(account_ownership_required, 'get')
# @method_decorator(account_ownership_required, 'post')



@method_decorator(has_ownership, 'get')        # get 메서드에 해주겟다는말
@method_decorator(has_ownership, 'post')       # decorate : 데코레이터의 리스트도 받음
# 이거 쓰면 함수쓰고 로그인 여부만 확인
class AccountUpdateView(UpdateView):
    model = User
    form_class = AccountCreationForm
    context_object_name = 'target_user'    # 어떤 객체를 불러올 건지
    # success_url = reverse_lazy ('accountapp:hello_world')
    # 수정 후 어디론가 재연결 할지
    template_name = 'accountapp/update.html'
    # 어떤 경로의 html 을 쓸건지

    def get_success_url(self):
        return reverse('accountapp:detail', kwargs={'pk': self.object.pk})
         # popo 자체가 계정앱이기때문에 user를 쓸 필요가 없음
        # object = target_user 이므로

@method_decorator(has_ownership, 'get')
@method_decorator(has_ownership, 'post')
class AccountDeleteView(DeleteView):
    model = User
    context_object_name = 'target_user'
    success_url = reverse_lazy('articleapp:list')
    template_name = 'accountapp/delete.html'




# 데코레이터 안할 시
    # def get(self, request, *args, **kwargs):
    #     if request.user.is_authenticated and self.get_object() == request.user:  # 로그인되었을 시
    #         return super().get(request, *args, **kwargs)
    #         # get라는 함수를 오버라이딩(쌍속) 하여 부모의 것을 받아 그대로 리턴
    #
    #     else:  # 로그인아닐 시
    #         return HttpResponseForbidden()
    #         # HttpResponseForbidden() : 금지한다
    #
    # def post(self, request, *args, **kwargs):
    #
    #     if request.user.is_authenticated and self.get_object() == request.user:  # 로그인되었을 시
    #         return super().post(request, *args, **kwargs)
    #         # get라는 함수를 오버라이딩(쌍속) 하여 부모의 것을 받아 그대로 리턴
    #
    #     else:  # 로그인아닐 시
    #         return HttpResponseForbidden()
    #         # HttpResponseForbidden() : 금지한다

accountapp/templates/accountapp/create.html
{# extends 구문을 사용#}
{% extends 'base.html' %}       {#base.html 에서 했던 뼈대 이름으로 하여금 #}

{% load bootstrap4 %}
{# 부트스트랩을 회원가입 창에다 쓰겠다는 이야기 #}

{% block content %}
{#제목#}
    <div class="text-center mw-500 m-auto">   {#부트스트랩에서 제공하는 텍스트 중앙 정렬 #}
        {# base.css 파일에서 mw-500 을 불러옴, m-auto : 부트스트랩안에있는 자동정렬 #}
        <div class="m-5">       {# 상하좌우 마진 5만큼 추가 #}
            <h4> Sign up</h4>           {#제목#}
        </div>
        <div>
{# 'popo:create'라는 말은 popo-urls의 'appname : name'를 이용하여 역추적하는것 이므로 urls 확인!! #}
            <form action="{% url 'accountapp:create' %}" method="post">
                {#어느 주소로 요청을 보낼건지 써야하는데 안쓰고 url 을 씀#}
                {% csrf_token %}
{#                {{ form }}  대신            {# 일반 출력할 때 #} {#양이 많을때 #}
                {% bootstrap_form form %}


               <div class = 'm-5'>
                   <input type="submit"
                       class="btn btn-dark rounded-pill px-5">
                {#트리거해줄 버튼을 생성 // 부트스트랩에서 서식을 따옴 #}
               </div>
            </form>

        </div>
    </div>


{%  endblock %}

accountapp/templates/accountapp/delete.html
{# extends 구문을 사용#}
{% extends 'base.html' %}       {#base.html 에서 했던 뼈대 이름으로 하여금 #}

{# 부트스트랩을 회원가입 창에다 쓰겠다는 이야기 #}

{% block content %}
{#제목#}
    <div class="text-center mw-500 m-auto">   {#부트스트랩에서 제공하는 텍스트 중앙 정렬 #}
        {# base.css 파일에서 mw-500 을 불러옴, m-auto : 부트스트랩안에있는 자동정렬 #}
        <div class="m-5">       {# 상하좌우 마진 5만큼 추가 #}
            <h4> Quit</h4>           {#제목#}
        </div>
        <div>
{# 'popo:create'라는 말은 popo-urls의 'appname : name'를 이용하여 역추적하는것 이므로 urls 확인!! #}
            <form action="{% url 'accountapp:delete' pk=target_user.pk %}" method="post">
                {#어느 주소로 요청을 보낼건지 써야하는데 안쓰고 url 을 씀#}
                {% csrf_token %}
{#                {{ form }}  대신            {# 일반 출력할 때 #} {#양이 많을때 #}

               <div class="m-5">
                   <input type="submit"
                       class="btn btn-danger rounded-pill px-5">
                {#트리거해줄 버튼을 생성 // 부트스트랩에서 서식을 따옴 #}
               </div>
            </form>

        </div>
    </div>


{%  endblock %}

accountapp/templates/accountapp/detail.html
{# extends 구문을 사용#}
{% extends 'base.html' %}       {#base.html 에서 했던 뼈대 이름으로 하여금 #}


{% block content %}
{#제목#}
    <div class="text-center mw-500 m-auto">   {#부트스트랩에서 제공하는 텍스트 중앙 정렬 #}
        {# base.css 파일에서 mw-500 을 불러옴, m-auto : 부트스트랩안에있는 자동정렬 #}
        <div class="m-5">       {# 상하좌우 마진 5만큼 추가 #}
            {% if target_user.profile %}
            {# 프로파일 존재하는지 #}
            {# 여기서 profile은 model.py의 related_name에서 지정한 이름을 따서옴 #}

                <img src="{{ target_user.profile.image.url }}"
                     class="profile_image m-4"  {# 클래스 이름 생성 #}
                     alt="profile image">
                {# 이미지 url을 따옴 , 만약 이미지가 없을 시 profile image 텍스트를 출력함함#}

               <h2 class="NNS_B">
                   {{ target_user.profile.nickname }} {# 존재한다면 보고자하는 계정의 아이디를 보고싶음#}
                        {% if target_user == user %}    {# 로그아웃 시 안보이도록 하게끔 하는 것 #}
                            <a href="{% url 'profileapp:update' pk=target_user.profile.pk %}"
                                class="material-icons round_button">
                                edit
                            </a>
                            {# 이파일 자체가 어카운트앱 파일이므로 그걸 먼저 쓰고 profile 을 연계해야함함 #}
                        {% endif %}
              </h2>

                <h5> {{ target_user.profile.message }}</h5>
                {#  메세지까지 출력 #}


            {% else %}
            <h2>
                <a href="{% url 'profileapp:create' %}">
                    Create Profile
                </a>

            </h2>
            {% endif %}

        </div>
{#        <div>#}
{#            {{ target_user.date_joined }}       {# date_joined : 언제 가입했는지 #}
{#        </div>#}

        {% if user == target_user %}
        {# 동일 인물 일 경우 업데이트와 delete 할 수 있도록 #}
        {#  로그아웃 된 상태 면 볼 수 없게 만듬 #}

        <div>
            <a href="{%  url 'accountapp:update' pk=target_user.pk  %}"
            class ="material-icons round_button mx-1">  {# mx-1 : 간격 #}
                settings
            </a>

            <a href="{%  url 'accountapp:delete' pk=target_user.pk  %}"
            class ="material-icons round_button mx-1">
                close
            </a>
        </div>
        {% endif %}
    </div>
    <div>
        {% include 'snippet/list_fragment.html' with article_list=object_list %}
    </div>


{%  endblock %}

accountapp/templates/accountapp/login.html
{# create.html 에서 거즘 다있으므로 복붙하고 고쳐주기 #}
{# extends 구문을 사용#}
{% extends 'base.html' %}       {#base.html 에서 했던 뼈대 이름으로 하여금 #}
{% load bootstrap4 %}
{% block content %}
{#제목#}
    <div class="text-center mw-500 m-auto">{#부트스트랩에서 제공하는 텍스트 중앙 정렬 #}
        <div class="m-5">       {# 상하좌우 마진 5만큼 추가 #}
            <h4> Login </h4>           {#제목#}
        </div>
        <div>
{# 'account:create'라는 말은 popo-urls의 'appname : name'를 이용하여 역추적하는것 이므로 urls 확인!! #}
            <form action="{% url 'accountapp:login' %}" method="post">
                {#어느 주소로 요청을 보낼건지 써야하는데 안쓰고 url 을 씀#}
                {% csrf_token %}
                {% bootstrap_form form %}

{#                {{ form }}                  {#양이 많을때 #}
               <div>
                   <input type="submit"
                       class="btn btn-dark rounded-pill px-5">
                {#트리거해줄 버튼을 생성 // 부트스트랩에서 서식을 따옴 #}
               </div>
            </form>

        </div>
    </div>


{%  endblock %}

accountapp/templates/accountapp/update.html
{# extends 구문을 사용#}
{% extends 'base.html' %}       {#base.html 에서 했던 뼈대 이름으로 하여금 #}

{% load bootstrap4 %}
{# 부트스트랩을 회원가입 창에다 쓰겠다는 이야기 #}

{% block content %}
{#제목#}
    <div class="text-center mw-500 m-auto">   {#부트스트랩에서 제공하는 텍스트 중앙 정렬 #}
        {# base.css 파일에서 mw-500 을 불러옴, m-auto : 부트스트랩안에있는 자동정렬 #}
        <div class="m-5">       {# 상하좌우 마진 5만큼 추가 #}
            <h4> Update Info </h4>           {#제목#}
        </div>
        <div>
{# 'popo:create'라는 말은 popo-urls의 'appname : name'를 이용하여 역추적하는것 이므로 urls 확인!! #}
            <form action="{% url 'accountapp:update' pk=target_user.pk %}" method="post">
                {#action : 어느 주소로 요청을 보낼건지 써야하는데 #}
                {% csrf_token %}
{#                {{ form }}  대신            {# 일반 출력할 때 #} {#양이 많을때 #}
                {% bootstrap_form form %}


               <div class="m-5">
                   <input type="submit"
                       class="btn btn-dark rounded-pill px-5">
                {#트리거해줄 버튼을 생성 // 부트스트랩에서 서식을 따옴 #}
               </div>
            </form>

        </div>
    </div>


{%  endblock %}