articleapp/urls.py
from django.urls import path
from django.views.generic import TemplateView

from articleapp.views import ArticleCreateView, ArticleDetailView, ArticleUpdateView, ArticleDeleteView, ArticleListView

app_name = 'articleapp'


urlpatterns =[
    path('list/', ArticleListView.as_view(), name='list'),

    path('create/', ArticleCreateView.as_view(), name='create'),
    path('detail/<int:pk>', ArticleDetailView.as_view(), name='detail'),
    path('update/<int:pk>', ArticleUpdateView.as_view(), name='update'),
    path('delete/<int:pk>', ArticleDeleteView.as_view(), name='delete'),


]

goHome/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

from articleapp.views import ArticleListView

urlpatterns = [
    path('', ArticleListView.as_view(), name='home'),
    path('admin/', admin.site.urls),        # 장고가 기본적으로 준 주소 (관리자 페이지)
    path('accounts/', include('accountapp.urls')),         #path = 장고에서 제공하는 기능 , 경로를 accounts
    path('profiles/', include('profileapp.urls')),
    # profiles 로가는 겨올를 설정
    path('articles/', include('articleapp.urls')),
    path('comments/', include('commentapp.urls')),
    path('projects/', include('projectapp.urls')),
    path('subscribe/', include('subscribeapp.urls')),
    path('likes/', include('likeapp.urls')),

] + static(settings.MEDIA_URL, document_root = settings.MEDIA_ROOT )
# 이미지 모양을 되기 위해 media 에 static 을 가져옴
# 경로로 왔을 때, 미디어를 제공

projectapp/urls.py
from django.urls import path

from projectapp.views import ProjectCreateView, ProjectDetailView, ProjectListView

app_name='projectapp'

urlpatterns =[

    path('create/', ProjectCreateView.as_view(), name='create'),
    path('detail/<int:pk>', ProjectDetailView.as_view(), name='detail'),
    path('list/', ProjectListView.as_view(), name='list'),
]

subscribeapp/urls.py
# from django.urls import path
from django.urls import path

from subscribeapp.views import SubscriptionView, SubscriptionListView

app_name = 'subscribeapp'
urlpatterns = [

    path('subscribe/<int:project_pk>', SubscriptionView.as_view(), name='subscribe'),

    path('list/', SubscriptionListView.as_view(), name='list'),
]

articleapp/models.py
from django.contrib.auth.models import User
from django.db import models

# Create your models here.
from projectapp.models import Project


class Article(models.Model):
    writer = models.ForeignKey(User, on_delete=models.SET_NULL, related_name='article',      # 접근할 이름 target_user.article 이렇게 됨
    null=True)
        # 1대 다로 테이블과 테이블을 연결함  ,,, User 을 연결
        # on_delete : user 가 삭제 되었을 떄 하는 것
        # null 값도 ok 하다는 것임

    project = models.ForeignKey(Project, on_delete=models.SET_NULL,
                                related_name='article', null=True, blank=True)

    title = models.CharField(max_length=200, null=True)
    image =models.ImageField(upload_to='article/', null=True)
    # media 파일 안에 article 이라는 폴더가 생기고 그 안에 사진이 자동으로 업로드됨

    content = models.TextField(null=True)
    #  TextField: 장문을 이용 시 사용

    created_at = models.DateField(auto_now_add=True, null=True)
    # DateField : 언제작성했는지 알 수 있음
    # auto_now_add : 자동으로 시간을 작성해줌줌

    like = models.IntegerField(default=0)

projectapp/models.py
from django.db import models

# Create your models here.


class Project(models.Model):
    name = models.CharField(max_length=20, null=False)
    description = models.CharField(max_length=200, null=False, blank=True)
    image = models.ImageField(upload_to='project/', null=False)

    created_at = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return f'{self.name}'
        # migration 을 안해줘도 됨
        # migration -> 모델에서 반영한 것에 DB에도 반영하게끔하려한 것
        # str 은 파이썬 내부에서 사용하는 방식이기 때문에 안해도 됨

projectapp/forms.py
from django.forms import ModelForm

from projectapp.models import Project


class ProjectCreationForm(ModelForm):
    class Meta:
        model = Project
        fields =['name', 'image', 'description']

projectapp/views.py
from django.contrib.auth.decorators import login_required
from django.shortcuts import render

# Create your views here.
from django.urls import reverse_lazy, reverse
from django.utils.decorators import method_decorator
from django.views.generic import CreateView, DetailView, ListView
from django.views.generic.list import MultipleObjectMixin

from articleapp.models import Article
from projectapp.forms import ProjectCreationForm
from projectapp.models import Project
from subscribeapp.models import Subscription


@method_decorator(login_required, 'get')
@method_decorator(login_required, 'post')
class ProjectCreateView(CreateView):
    model = Project
    form_class = ProjectCreationForm

    template_name = 'projectapp/create.html'

    def get_success_url(self):
        return reverse('projectapp:detail', kwargs={'pk':self.object.pk})

class ProjectDetailView(DetailView, MultipleObjectMixin):
    model = Project
    context_object_name = 'target_project'
    template_name = 'projectapp/detail.html'

    paginate_by = 20

    # 객체의 리스트를 돌려줌
    def get_context_data(self, **kwargs):
        # 어떤 유저가 어떤 게시물에 구독했는지 정의 시
        user = self.request.user
        project = self.object  # = target_project 와 같음

        # 로그인 여부 확인
        if user.is_authenticated:
            subscription = Subscription.objects.filter(user=user,
                                                       project=project)
        else:
            subscription = None

        article_list = Article.objects.filter(project=self.object)      # Article = DB
        return super().get_context_data(object_list=article_list,
                                        subscription=subscription,
                                        **kwargs)
                        # object_list : 장고에서 지원해주는것

class ProjectListView(ListView):
    model = Project
    context_object_name = 'project_list'
    template_name = 'projectapp/list.html'
    paginate_by = 20

projectapp/templates/projectapp/create.html
{# extends 구문을 사용#}
{% extends 'base.html' %}       {#base.html 에서 했던 뼈대 이름으로 하여금 #}

{% load bootstrap4 %}
{# 부트스트랩을 회원가입 창에다 쓰겠다는 이야기 #}

{% block content %}
{#제목#}
    <div class="text-center mw-500 m-auto">   {#부트스트랩에서 제공하는 텍스트 중앙 정렬 #}
        {# base.css 파일에서 mw-500 을 불러옴, m-auto : 부트스트랩안에있는 자동정렬 #}
        <div class="m-5">       {# 상하좌우 마진 5만큼 추가 #}
            <h4> Create Project</h4>           {#제목#}
        </div>
        <div>
{# 'popo:create'라는 말은 popo-urls의 'appname : name'를 이용하여 역추적하는것 이므로 urls 확인!! #}
            <form action="{% url 'projectapp:create' %}" method="post" enctype="multipart/form-data">
                {#어느 주소로 요청을 보낼건지 써야하는데 안쓰고 url 을 씀#}
                {% csrf_token %}
{#                {{ form }}  대신            {# 일반 출력할 때 #} {#양이 많을때 #}
                {% bootstrap_form form %}


               <div class = 'm-5'>
                   <input type="submit"
                       class="btn btn-dark rounded-pill px-5">
                {#트리거해줄 버튼을 생성 // 부트스트랩에서 서식을 따옴 #}
               </div>
            </form>

        </div>
    </div>


{%  endblock %}

projectapp/templates/projectapp/detail.html
{# extends 구문을 사용#}
{% extends 'base.html' %}       {#base.html 에서 했던 뼈대 이름으로 하여금 #}


{% block content %}
{#제목#}
    <div class="text-center mw-500 m-auto">   {#부트스트랩에서 제공하는 텍스트 중앙 정렬 #}
        {# base.css 파일에서 mw-500 을 불러옴, m-auto : 부트스트랩안에있는 자동정렬 #}
        <div class="m-5">       {# 상하좌우 마진 5만큼 추가 #}
                <img src="{{ target_project.image.url }}"
                     class="profile_image m-4"  {# 클래스 이름 생성 #}
                     alt="profile image">
                {# 이미지 url을 따옴 , 만약 이미지가 없을 시 profile image 텍스트를 출력함함#}

               <h2 class="NNS_B">
                   {{ target_project.name }} {# 존재한다면 보고자하는 계정의 아이디를 보고싶음#}
              </h2>
                <h5> {{ target_project.description }}</h5>
        </div>
    </div>

    {% if user.is_authenticated %}
    <div class="text-center">
        {% if not subscription %}
        <a href="{% url 'subscribeapp:subscribe' project_pk=target_project.pk %}"
        class="btn btn-primary rounded-pill px-5">   {# 버튼누를시 가는 경로 #}
            Subscribe
        </a>
        {% else %}
        <a href="{% url 'subscribeapp:subscribe' project_pk=target_project.pk %}"
        class="btn btn-secondary rounded-pill px-5">   {# 버튼누를시 가는 경로 #}
            UnSubscribe
        </a>
        {% endif %}
    </div>
    {% endif %}
    <div>
        {% include 'snippet/list_fragment.html' with article_list=object_list %}
                {#이 경로로 저장되게끔  #}
    </div>

    <div>
    {% include 'snippet/list_fragment.html' with article_list=object_list %}
                {#이 경로로 저장되게끔  #}
    </div>


{%  endblock %}

projectapp/templates/projectapp/list.html
{% extends 'base.html'%}
{# 뼈대 html 을 가져옴 #}
{% load static %}
{# static 불러온다는 문구#}


{% block content %}
    <style>
        .container{
            padding: 0;
            margin: 0 auto;
        }
        .container div {
          display: flex;
          justify-content: center;
          align-items: center;
          border-radius: 1rem;
                flex-direction: column;
                {# 아래쪽으로 밑에 제목이 나오도록 // 기본값은 오른쪽임(행 = row )   #}

        }

        .container img{
            width: 7rem;        {# 너비는 다 채우겠다 #}
            height: 7rem;
            object-fit: cover;
            border-radius: 1rem;

        }

    </style>


    <div class="container my-4">        {# my : 마진 상하 #}
       {% for project in project_list %}
          <div>
            <a href="{% url 'projectapp:detail' pk=project.pk %}">
                <img src="{{ project.image.url }}" alt="">
            </a>
          <span class="my-2 NNS_B">{{ project.name | truncatechars:10 }}</span>


          </div>



       {% endfor %}
    </div>

    <script src="{% static 'js/magicgrid.js' %}">    </script>
{# static 안에 있는 자바스크립트 파일 호출 시 #}


    {% include 'snippet/pagination.html' %}

    <div class="text-center my-5">
        <a href="{% url 'articleapp:create' %}"
            class="btn btn-outline-dark rounded-pill px-5">
            {#  px-5 : 글씨를 좌우여백 조정 #}
            Create Project
        </a>

    </div>
{% endblock %}