accountapp/urls.py
from django.urls import path

from accountapp.views import  AccountCreateView, AccountDetailView, AccountUpdateView, AccountDeleteView

from django.contrib.auth.views import LoginView, LogoutView

app_name = 'accountapp'

urlpatterns = [
    path('login/', LoginView.as_view(template_name= 'accountapp/login.html'),
         name= 'login'  ),
    #path (어떤주소로 들어올건지, 함수(클래스시: 클래스이름.as_view), 우리가 쓸 라우트의 이름)

    path('logout/', LogoutView.as_view(), name='logout'),

    path('create/', AccountCreateView.as_view(), name = 'create'),
    #path ( 파일 이름, 함수(클래스시: 클래스이름.as_view), 우리가 쓸 이름을 설정)
    # 어떤 url 로 가야 회원가입 로직으로 가는지


    # detailView 만든 후 라우팅
    path('detail/<int:pk>', AccountDetailView.as_view(), name = 'detail' ),
    # 어떤주소로 접글할때 로직을 실행할건지 / 로직  / 라우트의 이름
    # int : pk  = 인티저 형태를 받는데 이름은 pk 이다

    path('update/<int:pk>', AccountUpdateView.as_view(), name ='update'),
    # 어떤주소로 접근할지 / 로직 / 라우트의 이름

    path('delete/<int:pk>', AccountDeleteView.as_view(), name = 'delete')
]
# 앱 네임이 accountapp 인걸로 가서 url이 hello_world 로 가라

articleapp/urls.py
from django.urls import path
from django.views.generic import TemplateView

from articleapp.views import ArticleCreateView, ArticleDetailView, ArticleUpdateView, ArticleDeleteView, ArticleListView

app_name = 'articleapp'


urlpatterns =[
    path('list/', ArticleListView.as_view(), name='list'),

    path('create/', ArticleCreateView.as_view(), name='create'),
    path('detail/<int:pk>', ArticleDetailView.as_view(), name='detail'),
    path('update/<int:pk>', ArticleUpdateView.as_view(), name='update'),
    path('delete/<int:pk>', ArticleDeleteView.as_view(), name='delete'),


]

goHome/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

from articleapp.views import ArticleListView

urlpatterns = [
    path('', ArticleListView.as_view(), name='home'),
    path('admin/', admin.site.urls),        # 장고가 기본적으로 준 주소 (관리자 페이지)
    path('accounts/', include('accountapp.urls')),         #path = 장고에서 제공하는 기능 , 경로를 accounts
    path('profiles/', include('profileapp.urls')),
    # profiles 로가는 겨올를 설정
    path('articles/', include('articleapp.urls')),
    path('comments/', include('commentapp.urls')),
    path('projects/', include('projectapp.urls')),
    path('subscribe/', include('subscribeapp.urls')),
    path('likes/', include('likeapp.urls')),

] + static(settings.MEDIA_URL, document_root = settings.MEDIA_ROOT )
# 이미지 모양을 되기 위해 media 에 static 을 가져옴
# 경로로 왔을 때, 미디어를 제공

projectapp/urls.py
from django.urls import path

from projectapp.views import ProjectCreateView, ProjectDetailView, ProjectListView

app_name='projectapp'

urlpatterns =[

    path('create/', ProjectCreateView.as_view(), name='create'),
    path('detail/<int:pk>', ProjectDetailView.as_view(), name='detail'),
    path('list/', ProjectListView.as_view(), name='list'),
]

subscribeapp/urls.py
# from django.urls import path
from django.urls import path

from subscribeapp.views import SubscriptionView, SubscriptionListView

app_name = 'subscribeapp'
urlpatterns = [

    path('subscribe/<int:project_pk>', SubscriptionView.as_view(), name='subscribe'),

    path('list/', SubscriptionListView.as_view(), name='list'),
]

templates/base.html
<!DOCTYPE html>
<html lang="en">

{% include 'head.html' %}

<body style="font-family: 'NanumSquareR'">
{# 모든 웹 화면에서 나눔스퀘어 폰트를 쓰도록#}

{% include 'header.html'  %}        {#  장고가 개입해서 사용하겠다라는 표시#}
<hr>                                {# 구분선 넣기 #}

{% for message in messages %}   {# 장고에서 기존적으로 제공함 #}
    <div class="text-center">
        <div class="btn btn-{{ message.tags }} rounded-pill px-5">
            {{ message }}
        </div>
    </div>
{% endfor %}

{% block content %}                 {# block content 를 선언 #}
{% endblock %}

<hr>

{% include 'footer.html' %}          {# include : 고정적인 것을 html 파일로로대체#}



</body>
</html>

templates/footer.html
<div style="text-align: center">
    <div class="pragmatic_footer_button">
        <span> 공지사항 </span>
        <span> 제휴 문의 </span>
        <span> 서비스 소개 </span>

    </div>
    <div class="pragmatic_footer_logo">
        <h5>pragmatic</h5>

    </div>
</div>

templates/head.html
{% load static %}               {# static 파일을 로드한다 #}

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <title>Title</title>


    {#  Bootstap link 부트스트랩 링크 넣어주는 곳 #}
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-EVSTQN3/azprG1Anm3QDgpJLIm9Nao0Yz1ztcQTwFspd3yD65VohhpuuCOmLASjC" crossorigin="anonymous">

    {# 구글 폰트 링크 넣어주는 곳 #}

    <link rel="preconnect" href="https://fonts.googleapis.com">
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
    <link href="https://fonts.googleapis.com/css2?family=Anton&display=swap" rel="stylesheet">

{#     default css link   #}        {#  디폴트 css 링크를 걸음  #}
    <link rel="stylesheet" type="text/css" href="{% static 'base.css' %}">


    {#  알아서 가져올 사이트를 제공 텍스트 파일을 가져올건데 css확장자로 가져올 거라는 말임 #}

    {# 강사님이 제공해준 폰트 서식 (안외워도 ok)    #}
    {#  모든 페이지에 적용됨 #}


{#  material icons link  #}
    <link href="https://fonts.googleapis.com/css2?family=Material+Icons"
      rel="stylesheet">


    <style>
        @font-face {        {# 폰트선언 #}
            font-family: 'NanumSquareR';        {# family : 그 나눔체로 선언하여 폰트에 적용 #}
            src: local('NanumSquareR'),
            url("{% static 'fonts/NanumSquareR.otf' %}") format("opentype");
        {# local : 우리 서버로 요청보내는 컴퓨터에서 나눔스퀘어라는 폰트가 있는지 찾고 있으면 적용 #}
        {# local에서 폰트가 없으면 url로 이동하여 적용 시켜라 #}
        }
        @font-face {
            font-family: 'NanumSquareEB';
            src: local('NanumSquareEB'),
            url("{% static 'fonts/NanumSquareEB.otf' %}") format("opentype");
        }
        @font-face {
            font-family: 'NanumSquareB';
            src: local('NanumSquareB'),
            url("{% static 'fonts/NanumSquareB.otf' %}") format("opentype");
        }
        @font-face {
            font-family: 'NanumSquareL';
            src: local('NanumSquareL'),
            url("{% static 'fonts/NanumSquareL.otf' %}") format("opentype");
        }
    </style>

</head>

templates/header.html
<div style="text-align: center">
    <div class="pragmatic_header_logo">
        <h1>
            <a href="{% url 'home'%}">
            Moms Touch
            </a>
        </h1>
    </div>

    <div class ="pragmatic_header_button">

        <span class="mx2">
            <a href="{% url 'articleapp:list' %}">
                Article
            </a>
        </span>                   {#좌우로 나열되게함#}
        <span class="mx2">
            <a href="{% url 'projectapp:list' %}">
                Projects
            </a>
        </span>
        {% if user.is_authenticated %}
        <span class="mx2">
            <a href="{% url 'subscribeapp:list' %}">
                Subscription
            </a>
        </span>
        {% endif %}

 {# 로그인 여부에따라 로그인이랑 회원가입이 보이고 안보이게 하는법 #}
        {% if not user.is_authenticated %}
        {# 로그인 안되있는 상태라면 /// user: 장고에서 어디서든 사용 ok #}
        <span class="mx2">
            <a href="{% url 'accountapp:login' %}">
                Login {# 로그인 창으로 이동 #}
            </a>{# 어디로 갈때 쓰는 태그 : a #}
        </span>
        <span class="mx2">
            <a href="{% url 'accountapp:create' %}">
            Sign up{# 회원가입 창으로 이동 #}
            </a>
        </span>


        {% else %}      {# 로그인 한 상태라면면 #}
        <span class="mx2">
           <a href="{% url 'accountapp:detail' pk=user.pk %}">
                MyPage
            </a>

        </span>
        <span class="mx2">
           <a href="{% url 'accountapp:logout' %}">
                Logout
            </a>

        </span>
        {% endif %}
    </div>

</div>