articleapp/urls.py
from django.urls import path
from django.views.generic import TemplateView

from articleapp.views import ArticleCreateView, ArticleDetailView, ArticleUpdateView, ArticleDeleteView, ArticleListView

app_name = 'articleapp'


urlpatterns =[
    path('list/', ArticleListView.as_view(), name='list'),

    path('create/', ArticleCreateView.as_view(), name='create'),
    path('detail/<int:pk>', ArticleDetailView.as_view(), name='detail'),
    path('update/<int:pk>', ArticleUpdateView.as_view(), name='update'),
    path('delete/<int:pk>', ArticleDeleteView.as_view(), name='delete'),


]

commentapp/urls.py
from django.urls import path

from commentapp.views import CommentCreateView, CommentDeleteView

app_name = 'commentapp'
urlpatterns =[
    path('create/', CommentCreateView.as_view(), name='create'),
    path('delete/<int:pk>', CommentDeleteView.as_view(), name='delete')


]

goHome/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

from articleapp.views import ArticleListView

urlpatterns = [
    path('', ArticleListView.as_view(), name='home'),
    path('admin/', admin.site.urls),        # 장고가 기본적으로 준 주소 (관리자 페이지)
    path('accounts/', include('accountapp.urls')),         #path = 장고에서 제공하는 기능 , 경로를 accounts
    path('profiles/', include('profileapp.urls')),
    # profiles 로가는 겨올를 설정
    path('articles/', include('articleapp.urls')),
    path('comments/', include('commentapp.urls')),
    path('projects/', include('projectapp.urls')),
    path('subscribe/', include('subscribeapp.urls')),
    path('likes/', include('likeapp.urls')),

] + static(settings.MEDIA_URL, document_root = settings.MEDIA_ROOT )
# 이미지 모양을 되기 위해 media 에 static 을 가져옴
# 경로로 왔을 때, 미디어를 제공

likeapp/urls.py
from django.urls import path

from likeapp.views import LikeArticleView

app_name = 'likeapp'

urlpatterns = [
    path('article/<int:article_pk>', LikeArticleView.as_view(), name='article_like'),

]

articleapp/models.py
from django.contrib.auth.models import User
from django.db import models

# Create your models here.
from projectapp.models import Project


class Article(models.Model):
    writer = models.ForeignKey(User, on_delete=models.SET_NULL, related_name='article',      # 접근할 이름 target_user.article 이렇게 됨
    null=True)
        # 1대 다로 테이블과 테이블을 연결함  ,,, User 을 연결
        # on_delete : user 가 삭제 되었을 떄 하는 것
        # null 값도 ok 하다는 것임

    project = models.ForeignKey(Project, on_delete=models.SET_NULL,
                                related_name='article', null=True, blank=True)

    title = models.CharField(max_length=200, null=True)
    image =models.ImageField(upload_to='article/', null=True)
    # media 파일 안에 article 이라는 폴더가 생기고 그 안에 사진이 자동으로 업로드됨

    content = models.TextField(null=True)
    #  TextField: 장문을 이용 시 사용

    created_at = models.DateField(auto_now_add=True, null=True)
    # DateField : 언제작성했는지 알 수 있음
    # auto_now_add : 자동으로 시간을 작성해줌줌

    like = models.IntegerField(default=0)

articleapp/forms.py
from django import forms
from django.forms import ModelForm

from articleapp.models import Article


class ArticleCreationForm(ModelForm):
    # 내용형식
    content = forms.CharField(widget=forms.Textarea(attrs={'class': 'editable',
                                                           'style': 'min-height: 10rem;'
                                                           'text-align: left;'}))


    class Meta:
        model = Article
        fields =['title', 'image', 'project', 'content']

articleapp/views.py
from django.contrib.auth.decorators import login_required
from django.shortcuts import render

# Create your views here.
from django.urls import reverse_lazy, reverse
from django.utils.decorators import method_decorator
from django.views.generic import CreateView, DetailView, UpdateView, DeleteView, ListView
from django.views.generic.edit import FormMixin

from articleapp.decorators import article_ownership_required
from articleapp.forms import ArticleCreationForm
from articleapp.models import Article


# login_required : 장고에서 지원함 ( 로그인 여부에 따라 인증과정 실시 )
from commentapp.forms import CommentCreationForm


@method_decorator(login_required, 'get')
@method_decorator(login_required, 'post')
class ArticleCreateView(CreateView):
    model = Article
    form_class = ArticleCreationForm
    template_name = 'articleapp/create.html'
    # 어떤걸 가지고 할건지

    def form_valid(self, form):
        form.instance.writer = self.request.user
        return super().form_valid(form)

    def get_success_url(self):
        return reverse('articleapp:detail', kwargs={'pk':self.object.pk})


class ArticleDetailView(DetailView, FormMixin):
    model = Article
    form_class = CommentCreationForm
    context_object_name = 'target_article'
    template_name = 'articleapp/detail.html'

@method_decorator(article_ownership_required, 'get')
@method_decorator(article_ownership_required, 'post')
class ArticleUpdateView(UpdateView):
    model = Article
    form_class = ArticleCreationForm            # create 폼을 쓴다는 이야기임
    context_object_name = 'target_article'
    template_name =  'articleapp/update.html'

    def get_success_url(self):
        return reverse('articleapp:detail', kwargs={'pk': self.object.pk})

@method_decorator(article_ownership_required, 'get')
@method_decorator(article_ownership_required, 'post')
class ArticleDeleteView(DeleteView):
    model = Article
    context_object_name = 'target_article'
    success_url = reverse_lazy('articleapp:list')
    template_name = 'articleapp/delete.html'

class ArticleListView(ListView):
    model =Article
    context_object_name = 'article_list'
    template_name = 'articleapp/list.html'
    paginate_by = 20
    # 1페이지에 몇개의 그림을 담을 건지

articleapp/templates/articleapp/create.html
{# extends 구문을 사용#}
{% extends 'base.html' %}       {#base.html 에서 했던 뼈대 이름으로 하여금 #}
{% load static %}
{% load bootstrap4 %}
{# 부트스트랩을 회원가입 창에다 쓰겠다는 이야기 #}

{% block content %}
    <script src="//cdn.jsdelivr.net/npm/medium-editor@latest/dist/js/medium-editor.min.js"></script>
    <link rel="stylesheet" href="//cdn.jsdelivr.net/npm/medium-editor@latest/dist/css/medium-editor.min.css" type="text/css" media="screen" charset="utf-8">
    <link rel="stylesheet" href="{% static 'beagle.css' %}">

    {#제목#}
    <div class="text-center mw-500 m-auto">   {#부트스트랩에서 제공하는 텍스트 중앙 정렬 #}
        {# base.css 파일에서 mw-500 을 불러옴, m-auto : 부트스트랩안에있는 자동정렬 #}
        <div class="m-5">       {# 상하좌우 마진 5만큼 추가 #}
            <h4> Create Article</h4>           {#제목#}
        </div>
        <div>
{# 'popo:create'라는 말은 popo-urls의 'appname : name'를 이용하여 역추적하는것 이므로 urls 확인!! #}
            <form action="{% url 'articleapp:create' %}" method="post" enctype="multipart/form-data">
                {#어느 주소로 요청을 보낼건지 써야하는데 안쓰고 url 을 씀#}
                {% csrf_token %}
{#                {{ form }}  대신            {# 일반 출력할 때 #} {#양이 많을때 #}
                {% bootstrap_form form %}


               <div class = 'm-5'>
                   <input type="submit"
                       class="btn btn-dark rounded-pill px-5">
                {#트리거해줄 버튼을 생성 // 부트스트랩에서 서식을 따옴 #}
               </div>
            </form>

        </div>
    </div>
    <script>var editor = new MediumEditor('.editable');</script>

{%  endblock %}

articleapp/templates/articleapp/delete.html
{# extends 구문을 사용#}
{% extends 'base.html' %}       {#base.html 에서 했던 뼈대 이름으로 하여금 #}


{% block content %}
{#제목#}
    <div class="text-center mw-500 m-auto">   {#부트스트랩에서 제공하는 텍스트 중앙 정렬 #}
        {# base.css 파일에서 mw-500 을 불러옴, m-auto : 부트스트랩안에있는 자동정렬 #}
        <div class="m-5">       {# 상하좌우 마진 5만큼 추가 #}
            <h4> Delete Article : {{ target_article.title }}</h4>           {#제목#}
        </div>
        <div>
{# 'popo:create'라는 말은 popo-urls의 'appname : name'를 이용하여 역추적하는것 이므로 urls 확인!! #}
            <form action="{% url 'articleapp:delete' pk=target_article.pk %}" method="post">
                {#  pk=target_article.pk : update 뷰에는 꼭 써줘야함 #}
                {#어느 주소로 요청을 보낼건지 써야하는데 안쓰고 url 을 씀#}
                {% csrf_token %}
{#                {{ form }}  대신            {# 일반 출력할 때 #} {#양이 많을때 #}

               <div class = 'm-5'>
                   <input type="submit"
                          value="삭제하기"
                          {# 안에있는 delete 대신 삭제하기버튼이 나옴 #}
                       class="btn btn-danger rounded-pill px-5">
                {#트리거해줄 버튼을 생성 // 부트스트랩에서 서식을 따옴 #}
               </div>
            </form>

        </div>
    </div>


{%  endblock %}

articleapp/templates/articleapp/detail.html
{%  extends 'base.html' %}



{% block content %}

    <div class="container text-center">
        <div class="my-5">
            {# 게시글 제목, 글쓴이 , 작성일자 #}
            <h1 class="NNS_B"> {{ target_article.title }}</h1>
            <div class="my-3">
                 <a href="{% url 'likeapp:article_like' article_pk=target_article.pk %}"
                     class="material-icons" style="vertical-align: middle;
                     color : #f77; font-size: 1.4rem; ">   {# 수직정렬 #}
                    favorite
                 </a>
                <span>      {# 몇개 좋아요 되있는지 #}
                    {{ target_article.like }}
                </span>
            </div>
        <hr>        {#  구분선 그리기기 #}

       <div class="my-5">
            {#  게시글 대표이미지, 글 내용 #}
            <img src="{{ target_article.image.url }}"class =article_image
                 alt="">
                {# alt : 옆에 실행이 안되었을 경우 대체 할 것 #}
            <div class="my-5 article_content">
                {{ target_article.content |safe}}
            </div>

           {% if target_article.writer == user %}
               {# 로그인 아닌 사람들은 안보이게끔 함 #}
            <div>
                <a href="{% url 'articleapp:update' pk=target_article.pk %}"
                    class="btn btn-success rounded-pill px-5">
                    Update
                                    {# success :초록색 #}
                </a>
                 <a href="{% url 'articleapp:delete' pk=target_article.pk %}"
                    class="btn btn-danger rounded-pill px-5">
                    Delete

                </a>

            </div>
           {% endif %}
        </div>
            <hr>
        <div>
            {# 댓글 내옹, 작성란 #}
            {% for comment in target_article.comment.all %}
        {# target_article.comment : models.py 에서 외래키로(related name) 만든 이름임(comment)  #}
        {# all : comment 를 모두 가져오기 위함 #}
               <div class="comment_box">
                    <div>
                        {# 유저의 닉네임, 시간정보 #} {# 유저 이름만 폰트체조금 크게 하기 #}
                        <span class="NNS_B" style="font-size: 1.3rem;">
                            {{ comment.writer.profile.nickname }}</span>

                        <span>{{ comment.create_at }}</span>
                    </div>
                    <div>
                        {# 댓글 내용 #}
                        <p>{{ comment.content }}</p>{# p : 글을만들어줄때의 태그 #}
                    </div>
                   {% if comment.writer == user %}
                    <div style="text-align: right">
                        <a href="{% url 'commentapp:delete' pk=comment.pk %}"
                           class="btn btn-danger rounded-fill px-5">
                            Delete
                        </a>
                    </div>
                   {% endif %}{# 로그아웃상태일 시 안나오도록 함 #}
                </div>
            {% endfor %}
            {% include 'commentapp/create.html' %}

        </div>
    </div>


{% endblock %}

articleapp/templates/articleapp/list.html
{% extends 'base.html'%}
{# 뼈대 html 을 가져옴 #}
{% load static %}
{# static 불러온다는 문구#}


{% block content %}
    <style>
        .container{
            padding: 0;
            margin: 0 auto;
        }
        .container div {
          width: 45%;
            max-width: 200px;
          display: flex;
          justify-content: center;
          align-items: center;
          border-radius: 1rem;
                flex-direction: column;
                {# 아래쪽으로 밑에 제목이 나오도록 // 기본값은 오른쪽임(행 = row )   #}
          box-shadow: 0 0 1rem #7b2727;
        }

        .container img{
            width: 100%;        {# 너비는 다 채우겠다 #}
            border-radius: 1rem;

        }

    </style>


    <div class="container my-4">        {# my : 마진 상하 #}
       {% for article in article_list %}
          <div>
            <a href="{% url 'articleapp:detail' pk=article.pk %}">
                <img src="{{ article.image.url }}" alt="">
            </a>
          <span class="my-2 NNS_B">{{ article.title }}</span>


          </div>



       {% endfor %}
    </div>

    <script src="{% static 'js/magicgrid.js' %}">    </script>
{# static 안에 있는 자바스크립트 파일 호출 시 #}


    {% include 'snippet/pagination.html' %}

    <div class="text-center my-5">
        <a href="{% url 'articleapp:create' %}"
            class="btn btn-dark rounded-pill  material-icons">
            {#  px-5 : 글씨를 좌우여백 조정 #}
            {# material-icons : 아이콘 만들기 #}
            brush
        </a>

        <a href="{% url 'articleapp:create' %}"
            class="btn btn-outline-dark rounded-pill px-5">
            {#  px-5 : 글씨를 좌우여백 조정 #}
            Create Article
        </a>

    </div>
{% endblock %}

articleapp/templates/articleapp/update.html
{# extends 구문을 사용#}
{% extends 'base.html' %}       {#base.html 에서 했던 뼈대 이름으로 하여금 #}
{% load static %}
{% load bootstrap4 %}
{# 부트스트랩을 회원가입 창에다 쓰겠다는 이야기 #}

{% block content %}
    <script src="//cdn.jsdelivr.net/npm/medium-editor@latest/dist/js/medium-editor.min.js"></script>
    <link rel="stylesheet" href="//cdn.jsdelivr.net/npm/medium-editor@latest/dist/css/medium-editor.min.css" type="text/css" media="screen" charset="utf-8">
    <link rel="stylesheet" href="{% static 'beagle.css' %}">

{#제목#}
    <div class="text-center mw-500 m-auto">   {#부트스트랩에서 제공하는 텍스트 중앙 정렬 #}
        {# base.css 파일에서 mw-500 을 불러옴, m-auto : 부트스트랩안에있는 자동정렬 #}
        <div class="m-5">       {# 상하좌우 마진 5만큼 추가 #}
            <h4> Update Article</h4>           {#제목#}
        </div>
        <div>
{# 'popo:create'라는 말은 popo-urls의 'appname : name'를 이용하여 역추적하는것 이므로 urls 확인!! #}
            <form action="{% url 'articleapp:update' pk=target_article.pk %}" method="post" enctype="multipart/form-data">
                {#  pk=target_article.pk : update 뷰에는 꼭 써줘야함 #}
                {#어느 주소로 요청을 보낼건지 써야하는데 안쓰고 url 을 씀#}
                {% csrf_token %}
{#                {{ form }}  대신            {# 일반 출력할 때 #} {#양이 많을때 #}
                {% bootstrap_form form %}


               <div class = 'm-5'>
                   <input type="submit"
                       class="btn btn-dark rounded-pill px-5">
                {#트리거해줄 버튼을 생성 // 부트스트랩에서 서식을 따옴 #}
               </div>
            </form>

        </div>
    </div>
    <script>var editor = new MediumEditor('.editable');</script>


{%  endblock %}